# permissions to do viewer presentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presentation-viewer-role
rules:
- apiGroups:
  - example.meetup.com
  resources:
  - presentations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.meetup.com
  resources:
  - presentations/status
  verbs:
  - get
